# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BCC <- function(dat, R, id, n_obs, N, num_cluster, dist, alpha_common, sigma_sq_e_common, p, q, sig_var, ppi, alpha, zz, zz_local, gamma, sigma_sq_e, phi, sigma_sq_u, beta, delta, a_star, b_star, aa0, bb0, a0, b0, v0, V0, cc0, dd0, c0, d0, rr0, RR0, ww0, vv0, lambda0, Lambda0, LOG_LIK_ITER, PPI, ZZ, ALPHA, ZZ_LOCAL, GA, GA_ACCEPT, THETA, THETA_ACCEPT, SIGMA_SQ_U, SIGMA_SQ_E, T_LOCAL, T, adaptive_tunning, tunning_freq, c_gamma_tunning, c_beta_tunning, burn_in, thin, per, max_iter, seed_initial) {
    .Call(`_BCClong_BCC`, dat, R, id, n_obs, N, num_cluster, dist, alpha_common, sigma_sq_e_common, p, q, sig_var, ppi, alpha, zz, zz_local, gamma, sigma_sq_e, phi, sigma_sq_u, beta, delta, a_star, b_star, aa0, bb0, a0, b0, v0, V0, cc0, dd0, c0, d0, rr0, RR0, ww0, vv0, lambda0, Lambda0, LOG_LIK_ITER, PPI, ZZ, ALPHA, ZZ_LOCAL, GA, GA_ACCEPT, THETA, THETA_ACCEPT, SIGMA_SQ_U, SIGMA_SQ_E, T_LOCAL, T, adaptive_tunning, tunning_freq, c_gamma_tunning, c_beta_tunning, burn_in, thin, per, max_iter, seed_initial)
}

LL <- function(fit, fast_version) {
    .Call(`_BCClong_LL`, fit, fast_version)
}

